
#access key and secret key are stored in defualt profile(aws configure)
---
- hosts: localhost
  vars:
    region: eu-west-2
    size: 100
    instance_type: db.t2.micro
    db_engine: postgres
    db_name  : verint-testdb    
    engine_version: 9.4.5
    parameter_group: dbpg1
    rds_instance_name: verint-test-rds-pg-1
    username: dbadmin
    password: password

  tasks:
    - name: create a free trail S3 bucket
      s3_bucket:
        name: verint-test
        state: present
        versioning: no 
        tags:
          name: verint-test
          type: test
    

    - name: Create Free tier AWS RDS Postgres 
      local_action:
        module: rds
        command: create
        instance_name: "{{ rds_instance_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        instance_type: "{{ instance_type }}"
        db_engine: "{{ db_engine }}"
        multi_zone: no
        username: "{{ username }}"
        password: "{{ password }}"


